### ISSUE TITLE
Webhook error

### ISSUE THREAD

**Issue by jerome2710** [sanderdewijs/mollie-edd-addon#1]
Wanneer ik de gateway gebruik krijg ik de volgende error:
'API call failed: Error executing API call (request): The webhook location is invalid.' 

In Mollie heb ik geen webhook ingesteld, vandaar waarschijnlijk deze foutmelding. Welke URL zou ik daar in moeten vullen?

**Comment by sanderdewijs** [comment]
Hoi Jerome,

De webhook url wordt automatisch in de plugin aangemaakt en doorgegeven aan Mollie. 

Waar krijg je de foutmelding te zien? Is dit in het log van Mollie? Of op de website tijdens het uitvoeren van een betaling? 

Om te testen kun je ook de volgende webhook URL handmatig in je Mollie websiteprofiel meegeven: http://www.jouwwebsiteadres.nl/?edd-listener=MOLLIE

**Comment by sanderdewijs** [comment]
Het probleem wordt veroorzaakt doordat er nu geen / achter je website URL wordt gezet. Heb zojuist een update gemaakt met de gewijzigde code. Zou je deze eens kunnen testen op jouw website?

**Comment by jerome2710** [comment]
Hi Sander,

Bedankt voor je snelle reactie.
Deze melding krijg ik op een lege pagina in de website, na het invullen van mijn gegevens en het kiezen van de betalingsmethode. De URL in dit geval is dan '../afrekenen/?payment-mode=mollie_gateway'.

De update ga ik nu proberen!

**Comment by jerome2710** [comment]
Hi Sander,

Ik krijg nu de volgende melding;
Fatal error: Call to undefined function edd_set_payment_transaction_id() in ../public_html/wp-content/plugins/mollie-edd-addon/mollieEddGateway.php on line 143

Waarschijnlijk moet ik mijn EDD moet updaten, omdat ik een versie heb waar deze functie nog niet in zit. Voor maatwerk heb ik EDD flink aangepast, vandaar dat de plugin wat versies achterloopt.

Bedankt voor je hulp, ik ga ermee aan de slag!

**Comment by sanderdewijs** [comment]
Top! Inderdaad kan EDD de functie niet vinden. Die is volgens mij toegevoegd in één van de laatste versies. 

Maar als je wilt kun je die functie ook even weglaten. Dus regel 143 in de code even commenten. Die zorgt er alleen maar voor dat het Mollie ID ook wordt opgeslagen in de database. Meer als handigheidje dan essentieel voor het verrichten van een betaling. 

Zou dit eerst even proberen voordat je EDD zelf begint om te sleutelen :-)

**Comment by jerome2710** [comment]
Hi Sander,

Nogmaals dank! Door regel 143 te commenten kan ik inderdaad afreken via Mollie.
